services:
  custom_model_server:
    image: tensorflow/serving:latest
    container_name: custom_model_server
    ports:
      - "8501:8501"            # REST
    volumes:
      - ./models/custom_model:/models/custom_model
    command: >
      --model_name=custom_model
      --model_base_path=/models/custom_model
      --rest_api_port=8501

  webapp:
    build:
      context: .
      dockerfile: webapp.Dockerfile
    container_name: webapp
    environment:
      - TF_URL=http://custom_model_server:8501/v1/models/custom_model:predict
    ports:
      - "8000:8000"
    depends_on:
      - custom_model_server
